# Change these first
owner: ashishdotme # Your GitHub username
repo: status.ashish.me # Your Github repository name

# Add your sites here
sites:
  - name: Jobs [prod] API
    url: https://jobsapi.ashish.me/
  - name: Main [prod] API
    url: https://api.ashish.me/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.ashish.me
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/ashishdotme/assets/master/logo.png
  name: ashish.me
  introTitle: status.ashish.me
  introMessage: uptime monitor for my personal projects
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
